<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE chestarmours
    [
        <!ELEMENT chestarmours (chestarmour*)>
        <!ELEMENT chestarmour (name, defense)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT defense (#PCDATA)>
        ]>
<chestarmours>
    <chestarmour>
        <name>Leather Armour</name>
        <defense>10</defense>
    </chestarmour>
    <chestarmour>
        <name>Studded Leather Armour</name>
        <defense>10</defense>
    </chestarmour>
</chestarmours>